FROM mattermost/mattermost-team-edition:latest

USER root

RUN apt-get update && apt-get install -y jq

COPY custom-entrypoint.sh /custom-entrypoint.sh
RUN chmod +x /custom-entrypoint.sh

ENTRYPOINT ["/custom-entrypoint.sh"]
